<a href="https://colab.research.google.com/github/AbouCamara/15-Days-15-Projects/blob/main/GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cupy as cp
import cupyx.scipy.sparse
import numpy as np
from scipy import fft
array_cpu = np.random.randint(0, 255, size=(4000, 4000))
array_cpu.nbytes / 1e6
array_gpu = cp.asarray(array_cpu)
%timeit
cp.asarray(array_cpu)
type(array_gpu)

cupy._core.core.ndarray

In [ ]:
from cupyx.scipy import fft as fft_gpu
%timeit
fft_gpu.fftn(array_gpu)

In [5]:
fft_cpu = fft.fftn(array_cpu)
fft_sent_back = cp.asnumpy(fft_gpu.fftn(array_gpu))
np.allclose(fft_sent_back, fft_cpu)

True

In [6]:
type(np.max(array_gpu))

cupy._core.core.ndarray

In [7]:
cp.random.randint(0, 255, size=(4000, 4000))

array([[ 71,  44,  33, ..., 201, 135, 103],
       [  5, 129,  53, ...,   6, 135,  69],
       [135,  59, 150, ...,  22, 104,  22],
       ...,
       [  7, 103, 216, ..., 153, 227, 136],
       [212, 165, 169, ..., 229, 207, 154],
       [208, 141,  27, ..., 163, 171, 222]])

In [3]:
from numba import cuda
cuda.detect()

Found 1 CUDA devices
id 0            b'Tesla K80'                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 4
                              pci bus id: 0
Summary:
	1/1 devices are supported


True

In [5]:
array_cpu = np.random.randint(0, 10, size=(2000, 2000))
d_array = cuda.to_device(array_cpu)
d_array

In [6]:
cp.asarray(d_array)

array([[1, 5, 2, ..., 6, 0, 3],
       [1, 1, 5, ..., 2, 8, 9],
       [3, 9, 4, ..., 4, 1, 7],
       ...,
       [2, 3, 1, ..., 7, 3, 9],
       [1, 8, 0, ..., 0, 4, 3],
       [0, 6, 1, ..., 0, 6, 3]])

In [8]:
d_array.copy_to_host()

array([[1, 5, 2, ..., 6, 0, 3],
       [1, 1, 5, ..., 2, 8, 9],
       [3, 9, 4, ..., 4, 1, 7],
       ...,
       [2, 3, 1, ..., 7, 3, 9],
       [1, 8, 0, ..., 0, 4, 3],
       [0, 6, 1, ..., 0, 6, 3]])